### ISSUE TITLE
you can see other players shortly after they join an arena / respawn / rewind

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#100]
Reported by **#ff7c50lv*#0f775abrian** (17/03/2021 12:38:57)
  
  **Description:**
  when players join an arena, respawn after dying or rewind after dying, you can see them, even though carhide is on

  **Reproduction:**
  play and see

**Comment by qualiti** [comment]
This is expected behaviour. There is a short delay between the checks for the carhide to sustain a good performance.
We may add, that respawned players are in another dimension the whole time which will make them invisible at all times.
