### ISSUE TITLE
orange loading bar is gone

### ISSUE THREAD

**Issue by brianmta** [Lumiverse/Atlas-Issues#105]
orange loading bar is gone

play a map and look at the bottom of the screen and see its not there

**Comment by brianmta** [comment]
debugscript also stopped outputting files while loading them

**Comment by qualiti** [comment]
This was caused due to the change of our download server. The compression removed the Content-Length header from the responses and therefore the scripts couldn't determine the total downloaded value.

I have changed the compression method and that resolved the issue.
