### ISSUE TITLE
getting achievements youve already got before, with rewards

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#108]
Reported by **#ff7c50lv*#0f775abrian** (27/03/2021 20:10:38)
  
  **Description:**
  players keep getting their old achievemets again and getting rewards for them again.

  **Reproduction:**

**Comment by qualiti** [comment]
Actually this issue was posted before #130 but since I assigned the other issue to the milestone and linked a PR to it, I'll close this one.
