### ISSUE TITLE
Collisions of objects are not restored

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#110]
Reported by **#000000goko?** (02/04/2021 09:54:06)
  
  **Description:**
  We can go throught the places and random objects spawned also roadbugs.

  **Reproduction:**
  We can go throught the places and random objects spawned also roadbugs.

**Comment by qualiti** [comment]
This seems to be the same MTA issue that appeared a while back where the engineRestoreCOL function didn't work as intended anymore.

**Comment by qualiti** [comment]
Since this is not in our hands but in the hands of the MTA developers I'm going to close this.
