### ISSUE TITLE
improved map cooldown system

### ISSUE THREAD

**Issue by brianmta** [Lumiverse/Atlas-Issues#113]
implement an improved map cooldown system, which gives every map a cooldown that was played, regardless of whether it was bought, set, or played randomly.

- cooldown length TBD
- map on cooldown can never play randomly again until the cooldown expires / the servers runs out of maps without a cooldown
- if the server runs out of maps without a cooldown, x number of maps with the lowest cooldown time remaining get their cooldown removed - then the server plays one of those maps randomly
- maps on a cooldown that was set by it having been played randomly could either not get bought at all, or would have a higher price than 5k. (maybe the price could get lower and lower as the cooldown also gets lower and lower)

**Comment by brianmta** [comment]
Any map that gets played in the arena gets a cooldown, regardless of whether it had been bought, set, or played randomly / voted on in a map-voting at the end of a round. The cooldown could be 45 minutes - during these 45 minutes the map could not get bought or played randomly and it wouldn't appear in map-voting -> only maps without an active cooldown would appear in map-voting.

If the server runs out of maps to pick from, the 50 maps with the lowest cooldown time automatically get their cooldown removed, so they can be bought / voted on again.

A map that was put on cooldown by a random round / map-vote could get bought again on the Dashboard for an increased price. If the cooldown is between 30 and 45 minutes, then the maps' prices could get multiplied by 10; if it's between 15 and 30 minutes then multiplied by 5; if it's between 5 and 15 minutes then multiplied by 3, and if it's between 0 and 5 then multiplied by 2.

**Comment by qualiti** [comment]
Just to be sure: This feature is supposed to be applied to every arena except for HDM (see #112). Right?

**Comment by brianmta** [comment]
dismiss the part about buying a map thats on cooldown for now
