### ISSUE TITLE
wheels models being replaced by map scripts

### ISSUE THREAD

**Issue by brianmta** [Lumiverse/Atlas-Issues#116]
messed up car parts everywhere, multiple parts on top of each other, double wheeles, etc

**Comment by qualiti** [comment]
Screenshot? Reproduction?

**Comment by brianmta** [comment]
wheel models not loading: https://cdn.discordapp.com/attachments/785612601999622224/828892895977013258/unknown.png

**Comment by brianmta** [comment]
double wheels: https://pasteboard.co/JWdj4mI.png
