### ISSUE TITLE
suggestion: train a random map

### ISSUE THREAD

**Issue by qualiti** [Lumiverse/Atlas-Issues#124]
**Describe the feature**
In order to discover new maps we can implement a "train random map" button in the training panel. Since there is a lot of space anyways this shouldn't be a big deal.

![image](https://user-images.githubusercontent.com/17724335/115681251-a671fa80-a354-11eb-8fa1-e800a9eef720.png)

**Comment by brianmta** [comment]
i suggest a "select random map" button instead
