### ISSUE TITLE
VR in catch wont reset after map

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#136]
Reported by **#000000Er1k** (03/05/2021 11:52:09)
  
  **Description:**
  After typing vr the status stays the same between maps

  **Reproduction:**
  Nothing, probably event caused it

**Comment by qualiti** [comment]
VR Status as in the votes?

**Comment by qualiti** [comment]
> BurN — Today at 2:23 PM
Max count is 16
Even tho there are 5 of us
