### ISSUE TITLE
Keys doesnt work in Respawn

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#139]
Reported by **#ff3838flokkz#ffffffzs** (03/05/2021 19:24:01)
  
  **Description:**
  Sometimes when I train in respawn some keys doesnt work. I pressed space or s to drift or slow down and nothing happend.

  **Reproduction:**
  Tested respawn

**Comment by qualiti** [comment]
duplicate of #135
