### ISSUE TITLE
tops messing up in hdm

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#140]
Reported by **#ff7c50lv*#0f775abrian** (04/05/2021 08:16:17)
  
  **Description:**
  brian - track matters tops got "viped", new tops are being made while zoilo's old t1 shows up on the dashboard (maps list) but not in "details"

  **Reproduction:**
  play hdm kekekekek

**Comment by qualiti** [comment]
There is a duplicate of this (#202) but it is better documented so I'll be closing this one
