### ISSUE TITLE
garage: intercooler not removed on unequip

### ISSUE THREAD

**Issue by qualiti** [Lumiverse/Atlas-Issues#153]
**Describe the bug**
The intercooler from front bumpers (or just Riptide) is not being removed after unequipping it.

**To Reproduce**
1. Equip Riptide
2. Unequip Riptide
3. Check the intercooler

**Screenshots**
![image](https://user-images.githubusercontent.com/17724335/119834894-a25f6c80-bf00-11eb-9f52-c49c27e6e677.png)

**Additional context**
Reported by Ramsy

**Comment by xzihark** [comment]
Tried with Architrave and Walker and it's the same. Even tried to equip, join any room, back to garage to unequip and join any room again but nothing changed, intercooler still appears in stock front bumper.

**Comment by zjkdev** [comment]
> Tried with Architrave and Walker and it's the same. Even tried to equip, join any room, back to garage to unequip and join any room again but nothing changed, intercooler still appears in stock front bumper.

Thank you for the additional details @xzihark, a fix is planned for this already.
