### ISSUE TITLE
players can use language chat while muted

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#158]
Reported by **#ff7c50lv*#0f775abrian** (07/06/2021 11:12:53)
  
  **Description:**
  player reported he was able to chat in language chat while being muted on 6th May 2021. confirmation required

  **Reproduction:**
  mute a player and see them talk in language chat?

**Comment by brianmta** [comment]
https://cdn.discordapp.com/attachments/851418725495210005/851418736225026068/unknown.png

**Comment by brianmta** [comment]
![image](https://user-images.githubusercontent.com/74862135/121007516-5e872580-c792-11eb-9811-0e23fc6f5f90.png)
