### ISSUE TITLE
WFF events system giving out wrong points at the end of the round

### ISSUE THREAD

**Issue by brianmta** [Lumiverse/Atlas-Issues#162]
players have reported that they often receive the wrong points when finishing a round during the WFF Event in the DM room (e.g.: being the only player to pass the map yet getting points for 2nd place).

**Comment by brianmta** [comment]
![image](https://user-images.githubusercontent.com/74862135/121788678-7108c100-cbcf-11eb-82ae-bb3c89db59cd.png)

**Comment by qualiti** [comment]
This is caused by #198
