### ISSUE TITLE
suggestion: prevent repetitive chat messages

### ISSUE THREAD

**Issue by dnl-k** [Lumiverse/Atlas-Issues#190]
**Describe the feature you'd like to see in the Atlas gamemode.**
I think most people can agree that it's quite annoying.

Prevent sending the same message again. To make it a bit more friendly restrict it to a certain time limit (As in you can't send the same message within 10 seconds).
![image](https://user-images.githubusercontent.com/13049457/124275167-6e501a80-db42-11eb-8b0b-2b7f9802af82.png)

Also while we're at it, prevent messages from being sent too fast, also known as retards spamming their binds

**Comment by qualiti** [comment]
We have both of those already implemented. You can post 3 messages in a row until you are warned to stop repeating yourself and the Anti-Spam hits in after 5 messages.

**Comment by zjkdev** [comment]
Reopening this issue since the anti-spam system indeed needs adjustement regarding spamming of binds.
