### ISSUE TITLE
Nos on last map lets you spawn with nos on next map sometimes

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#20]
Reported by **lv*#FF453AairplaNe** (29/12/2020 19:29:31)
  
  **Description:**
  This has happened in Race. I believe this bug is known, but we couldn't reproduce it.

  **Reproduction:**
  adads

**Comment by qualiti** [comment]
Since this bug only appeared like once (and we are currently not focusing on race anyways) I'll close this issue until something like that happens again.
