### ISSUE TITLE
UI: Next map not properly reset

### ISSUE THREAD

**Issue by dnl-k** [Lumiverse/Atlas-Issues#204]
**Describe the bug**
Setting the next map just before it loads (like really close) causes it to still be set as the next map in the UI

**To Reproduce**
1. Join any arena
2. Purchase a map just before it's meant to be loaded

**Screenshots**

https://user-images.githubusercontent.com/13049457/126865113-ba84dfeb-81ce-48c7-b41b-34ce1515d9ef.mp4

**Comment by qualiti** [comment]
Duplicate of #60
