### ISSUE TITLE
userpanel: Redundant information in userpanel when not logged in

### ISSUE THREAD

**Issue by CreeX0rZ** [Lumiverse/Atlas-Issues#213]
**Describe the bug**
Placeholders appear in the userpanel if not logged in.

**To Reproduce**
1.  Play as Guest
2. Open User Panel

**Screenshots**
![image](https://user-images.githubusercontent.com/85842850/132895072-2c68caf6-e8db-41f9-82c2-c73d610269d1.png)

**Additional context**
Trivial issue.

**Comment by qualiti** [comment]
This is pretty much a duplicate of https://github.com/Lumiverse/Atlas-Issues/issues/123. Closing this one in favor of the other ticket.
