### ISSUE TITLE
into deep ii bug

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#215]
Reported by **.#330033#J#010101oeL** (17/09/2021 03:18:43)
  
  **Description:**
  teleport bug in this map, quad is underwater 

  **Reproduction:**
  when i get in some teleport

**Comment by qualiti** [comment]
This is caused by https://github.com/Lumiverse/Atlas-Issues/issues/119. Hence I'm closing this one
