### ISSUE TITLE
If a player finishes the map while burning, he'll explode on spawn and kill everyone

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#22]
Reported by **lv*#FF453AairplaNe** (29/12/2020 18:10:43)
  
  **Description:**
  That happened in race, I suppose he burnt at the end.

  **Reproduction:**
  sads

**Comment by qualiti** [comment]
I am not sure about when this issue was created but I doubt that this is still a thing. Whenever a map is being changed all of the current vehicles of the players are being destroyed and every player gets a new one.
