### ISSUE TITLE
event(team): Initial clan lost after team event is finished

### ISSUE THREAD

**Issue by CreeX0rZ** [Lumiverse/Atlas-Issues#222]
**Describe the bug**
Players will not get back to their clans after the team event is finished.

**To Reproduce**

1. Start a team event
2. Fill up the arena with players in clans
3. Finish the event
4. Observe that the players are clanless

**Screenshots**
![image](https://user-images.githubusercontent.com/85842850/134591179-888a4525-1e79-4db9-a555-6c6b6c4f0c15.png)

**Additional context**
Reconnecting helps.

**Comment by qualiti** [comment]
I believe this issue was fixed already recently. Keep an eye open and see if this still happens please!

**Comment by qualiti** [comment]
It's not 😞
