### ISSUE TITLE
decals: improve accessibility to the "buy more layers" key (+)

### ISSUE THREAD

**Issue by zjkdev** [Lumiverse/Atlas-Issues#223]
**Describe the bug**
Apparently the `+` key isn't accessible for every keyboards, so we need to find a way to make it more accessible from any keyboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/35749378/134697878-080d32f5-b011-437c-bc5d-d4678240e397.png)
![image](https://user-images.githubusercontent.com/35749378/134697887-e89f9e1f-d58e-4f57-bcd1-3601097f596b.png)

**Comment by pzrwk** [comment]
I don't think there's a workaround for this case. Players have to find "=" sign on their keyboard.
