### ISSUE TITLE
Flag carrier doesn't have the flag on him.

### ISSUE THREAD

**Issue by darkyzowo** [Lumiverse/Atlas-Issues#229]
*Describe the bug
The person carrying the flag (enemy player holding your flag), the blip shows who's carrying it but the flag itself is not visible on top of him. This is related to the "Flag not visible inside cylinder marker" bug. 

*To Reproduce

1) Start a new map and keep playing, eventually when you respawn the flag will become invisible, so anyone holding it won't have it on top of him.

**Screenshots**

![mta-screen_2021-10-13_21-18-09](https://user-images.githubusercontent.com/92459505/137174906-e4f311c6-e28d-466d-9d97-3a83ee7bcb64.png)

**Comment by qualiti** [comment]
That is related to #228. Since the flag is invisible you can't see it on top of the car as well
