### ISSUE TITLE
Cursor do not come out

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#230]
Reported by **#FF00FFJuanes** (21/10/2021 07:20:37)
  
  **Description:**
  Server default cursor not displayed

  **Reproduction:**
  Pls help:(

**Comment by qualiti** [comment]
I assume that the custom cursor we are using on our server is not displaying for you, right? If that's the case try to delete your local resources (especially _lvCursors) and restart your game (sometimes even a PC restart is necessary).
