### ISSUE TITLE
suggestion: CTF Rocket timer

### ISSUE THREAD

**Issue by Inspraa** [Lumiverse/Atlas-Issues#234]
Increase the rocket cooldown timer by 0.5 seconds

**Comment by qualiti** [comment]
(pm) from CIFFON[INT] (ID 26): we're used to solid 3 seconds
(pm) from CIFFON[INT] (ID 26): yours is between 2-3
(pm) from CIFFON[INT] (ID 26): 2-2.5*
(pm) from CIFFON[INT] (ID 26): nah I saw that Inspra wrote add 0.5 cooldown
(pm) from CIFFON[INT] (ID 26): just dk add to what, as to what is your current
