### ISSUE TITLE
Achievements: Percentages of some achievements are not getting updated

### ISSUE THREAD

**Issue by CreeX0rZ** [Lumiverse/Atlas-Issues#249]
**Describe the bug**
If there is progress made towards a couple of achievements, the percentage value next to them will not update - it will appear as "0%" at all times.

Affected achievements (so far):

- OS: Top Times
- King of events

**To Reproduce**

1. Join OS Arena (not sure for which one the achievement counts, A or B)
2. Pass a map (with a time faster than Top 9 I guess)
3. Press 'U' > Statistics > Achievements (might need to wait for Statistics update)
4. Observe that "OS: Top Times" value has increased, but percentage stays at 0% at all times.

**Screenshots**
![image](https://user-images.githubusercontent.com/85842850/162740635-1acb2acf-7394-4346-b0a1-f48bb27db0ea.png)

**Additional context**
List may be updated if issue will be noticed on other achievements.

**Comment by qualiti** [comment]
Although this might seem weird at first glance (considering you have 5 / 25 top times necessary for the achievement) this isn't a bug at all. We made the achievements work, so you can see the progress from one level to the next level (in this case, from level 2 to level 3). Level 2 in this case is 5 top time. Hence, you didn't make any progress after level 2 anymore towards level 3 which causes the 0% to appear.

If that wasn't clear enough, feel free to contact me :)
