### ISSUE TITLE
Catch: Holding the nos key while going on a nos pickup won't activate it

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#36]
Reported by **#FF7C50lv*#111111zjk!** (27/12/2020 00:38:17)
  
  **Description:**
  When you have nos already, if you hold your nos key and go through a nos pickup, the nos won't activate until you re-press the key which is kinda annoying.

  **Reproduction:**
  Simply join catch, get nos and hold your nos key while going through a nos pickup.

**Comment by tsprotte** [comment]
I expect the same behaviour in FDD and Race as the same nos script
