### ISSUE TITLE
Dashboard (admins): Cannot edit maps in Catch 

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#37]
Reported by **#FF7C50lv*#111111zjk!** (26/12/2020 23:56:42)
  
  **Description:**
  When I want to edit a map information in the dashboard "Maps" tab, the button doesn't trigger and throws debug errors.

  **Reproduction:**
  You can easily reproduce it by going in Dashboard > Maps when you're in the Catch room, and click on the "Edit" button.

**Comment by qualiti** [comment]
![image](https://user-images.githubusercontent.com/17724335/115718549-7ee25880-a37b-11eb-8263-ea70098b9704.png)
