### ISSUE TITLE
music isn't working on maps where it should

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#62]
Reported by **#ff7c50lv*#0f775abrian** (17/02/2021 09:21:28)
  
  **Description:**
  music should be fine, no reason not to work, no errors in debug, they just don't work. already happened on two maps. all i can do is completely replace the music file. one of them was mp3 the other m4a

  **Reproduction:**
  play the maps

**Comment by qualiti** [comment]
This was most likely related to our previous way of handling the downloads (which also handled the music streams). Since we changed our download server to a better one it should now be working properly.
