### ISSUE TITLE
garage items visible on maps

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#70]
Reported by **#ff7c50lv*#0f775abrian** (26/02/2021 11:43:32)
  
  **Description:**
  items we used to replace garage items with are visible on maps where people used them (e.g. Disaster v5 - Journey; Disaster ft. BriaN - ABZU)

  **Reproduction:**
  play a map from above

**Comment by zjkdev** [comment]
Since we are using vehicle parts models from the game, any map using these models in their scripts will need their model IDs to be changed to something else. (already discussed with @brianmta)
