### ISSUE TITLE
certain objects missing from the hidden-object-shower

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#71]
Reported by **#ff7c50lv*#0f775abrian** (26/02/2021 11:48:23)
  
  **Description:**
  objects that people use to prevent people from cheating on their maps using the hdden-object-shower are not added to the script, resulting in being able to show every invisible object and making certain maps pointless

  **Reproduction:**
  play gteatero's invisibles map and make the objects visible, you should see a ton of containers on the road

**Comment by brianmta** [comment]
9900
9587

**Comment by tsprotte** [comment]
I'll just quote my answer from discord here:

![image](https://user-images.githubusercontent.com/17724335/111356321-8a5da800-8688-11eb-8c5f-ed3309a303b2.png)
