### ISSUE TITLE
loading a warp often forgets every velocity attribute

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#72]
Reported by **#ff7c50lv*#0f775abrian** (26/02/2021 11:56:29)
  
  **Description:**
  many times in map testing (maybe training too), when you load a warp you just get put in a place without any momentum

  **Reproduction:**
  test maps in maptesting

**Comment by qualiti** [comment]
This issue doesn't seem to be appearing anymore. If anyone experienced it recently, feel free to comment.
