### ISSUE TITLE
you can open the f6 map testing menu anywhere

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#78]
Reported by **#ff7c50lv*#0f775abrian** (26/02/2021 12:30:07)
  
  **Description:**
  if you press f6 anywhere on the server the maptesting menu will come up regardless of where you are or what you are doing. very easy to make it get bugged

  **Reproduction:**
  press f6 anywhere

**Comment by qualiti** [comment]
Issue is not appearing anymore.
