### ISSUE TITLE
deleting a map from the FUN arenas through dashboard doesnt work

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#80]
Reported by **#ff7c50lv*#0f775abrian** (26/02/2021 12:32:36)
  
  **Description:**
  if you delete a map via dashboard from FDD or CATCH the map will stay in the arena even though you get the successful notification. it only works via /deletemap command

  **Reproduction:**
  delete a map from FDD or Catch

**Comment by tsprotte** [comment]
Duplicate of #1
