### ISSUE TITLE
Dashboard: Map filter don't work

### ISSUE THREAD

**Issue by qualiti** [Lumiverse/Atlas-Issues#92]
**Describe the bug**
The filters for maps in the map shop don't work anymore

**To Reproduce**
1. Filter by a category
2. Open map details
3. Go back to the map shop and filters won't work anymore

**Screenshots**
Not needed

**Additional context**
This was initially reported by Rezzy on Discord.

**Comment by brianmta** [comment]
related to: https://github.com/Lumiverse/Atlas-Issues/issues/126 ?
