### ISSUE TITLE
nos pickup bug again

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#96]
Reported by **#ff7c50lv*#0f775abrian** (12/03/2021 19:11:50)
  
  **Description:**
  they bugged agane

  **Reproduction:**
  they are agane buggeded

**Comment by pkfln** [comment]
@brianmta Do you have any video material / more detailed description or an older issue on Github for this?

**Comment by tsprotte** [comment]
The problem that this issue describes is, that nos pickups that are placed directly behind a vehicle change are not being picked up even tho it works fine in the default race resource. One example (to be fair a bad one) is all of skills at the vehicle change from NRG to Infernus.

Kenzo also reported this on this map: ![Screenshot](https://cdn.discordapp.com/attachments/748161999363506237/819900196846698516/unknown.png)
